### ISSUE TITLE
Floating point precision issue?

### ISSUE THREAD

**Issue by hallav** [jpiironen/dimreduce#2]
Hi,

thank you for this very handy and useful package! I have been using it for extracting features from sequencing data for classification purposes and most of the time the package has worked well. But occasionally the ispca function fails and gives the following error message

"[1] "Computing the supervised principal components.."
Error in FUN(X[[i]], ...) :
  Something went wrong: the active set became empty after screening.
Calls: function_that_calls_ISPCA -> ispca -> lapply -> FUN -> spcs -> lapply -> FUN
Execution halted"

function_that_calls_ISPCA is a function in my pipeline which calls ispca function from the dimreduce package. I believe that the source of this error are lines 78-81 from auxiliary.R, where variables that have score above a certain threshold are picked. Based on my debugging, there is probably a problem with floating point precision in this part of the code from line 80

`cand[scores[cand] >= th]`

which makes the comparison fail.

To be able to run the ispca function to my data, I fixed the problem locally by replacing the part above with

`cand[which(round(scores[cand] - th,10) >= 0)]`

With this change, I am able to run the ispca function to all my data without problems. It might not be the best way to fix it, but it seems to work. Unfortunately I cannot share the data set for reproducing the error as it is not a public data set.

Best regards,
Viivi Halla-aho

**Comment by jpiironen** [comment]
Hi! Thanks for reporting this. It seems it's exactly those lines in `auxiliary.R` that are causing the trouble. It can be a numerical issue as you pointed out. But just to check: what values are you using for arguments `thresh` and/or `nthresh` when calling function `ispca`? Or are you just using the defaults and the program still gives this error?

**Comment by hallav** [comment]
Hi! 

The only arguments I used in addition to `x` and `y ` were `nctot` and `normalize=TRUE`. So the default values for `thresh` and `nthresh` were used.

Br,
Viivi

**Comment by jpiironen** [comment]
Thanks. I now noticed that the default grid for `thresh` is actually different from that declared in the documentation. I now changed it so that it should match the documentation, which should also solve this issue. The change is now pushed to master, so would you mind installing the latest version of the package and try if it works for your dataset? I believe it should now work.

**Comment by jpiironen** [comment]
Hi @hallav, have you had time to try out the new version? Does it work for your case after the change?

**Comment by hallav** [comment]
Hi,
yes, I tested the new version now and it seems to work for the data set for which I got the error earlier. Thank you!

Br,
Viivi

**Comment by jpiironen** [comment]
Great, no problem 👍 I'll close the issue.
